#!/bin/bash
set -eu
set -o pipefail
apt-get update
apt-get install -y expect unattended-upgrades

# npt was replaced by systemd-timesyncd from Bionic
if [ "${DIB_RELEASE}" == "xenial" ]; then
    apt-get install -y ntp
fi
