#!/bin/bash

# Installation documentation can be found here:
# Nvidia:
#  * Tesla Drivers  - https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html#ubuntu-lts
#  * Cuda           - https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation
#  * nvidia-docker  - https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-the-nvidia-driver
# Tensorflow:
#  * Docker:        - https://www.tensorflow.org/install/gpu
#                   - https://www.tensorflow.org/install/docker
cat <<EOF > /usr/local/bin/ubuntu-install-gpu-deps.sh
#!/bin/bash

if [[ $(id -u) -ne 0 ]] ; then echo "Please run script as root" ; exit 1 ; fi

distribution=\$(. /etc/os-release;echo $ID$VERSION_ID )

# Add required packages and CUDA repository
echo "Install linux-headers..."
apt-get install -y linux-headers-\$(uname -r)
compact_distribution=\$(echo \$distribution | sed -e 's/\.//g')
wget https://developer.download.nvidia.com/compute/cuda/repos/\$compact_distribution/x86_64/cuda-\$compact_distribution.pin
mv cuda-\$compact_distribution.pin /etc/apt/preferences.d/cuda-repository-pin-600
apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/\$compact_distribution/x86_64/7fa2af80.pub
echo "deb http://developer.download.nvidia.com/compute/cuda/repos/\$compact_distribution/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list

# Install CUDA Drivers (includes nvidia-driver-X)
echo "Install cuda-drivers..."
apt-get update
apt-get install -y --no-install-recommends cuda-drivers

cp /lib/udev/rules.d/40-vm-hotadd.rules /etc/udev/rules.d
sed -i -e 's/SUBSYSTEM=="memory", ACTION=="add"/#SUBSYSTEM=="memory", ACTION=="add"/g' /etc/udev/rules.d/40-vm-hotadd.rules

echo "Install Nvidia Toolkit"
# Use of Docker Image is recommended: https://www.tensorflow.org/install/gpu
# Many interdependencies can be packed into the image what's difficult for VM only installation.
# Furthermore, it decreases the Ubuntu GPU Image size massively.
echo "Install docker..."
curl https://get.docker.com | sh && systemctl enable docker

curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - && curl -s -L https://nvidia.github.io/nvidia-docker/\$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

echo "Install nvidia-docker2 ..."
apt-get update
apt-get install -y nvidia-docker2

# Test GPU Acess via:
echo "docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu python -c \"import tensorflow as tf; print('Num GPUs Available: ', len(tf.config.list_physical_devices('GPU')))\" "
echo "docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu python -c \"import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))\" "

echo "Reboot in 15 seconds ..."
sleep 15
echo "Reboot!"
reboot now

EOF

chmod 0755 /usr/local/bin/ubuntu-install-gpu-deps.sh
chown root:root /usr/local/bin/ubuntu-install-gpu-deps.sh
