#!/bin/bash

if [ "${DIB_RELEASE}" == "bionic" ]; then
    distribution="ubuntu18.04"
elif [ "${DIB_RELEASE}" == "focal" ]; then
    distribution="ubuntu20.04"
else
    distribution="ubuntu18.04"
fi

# Add required packages and CUDA repository
apt-get install -y linux-headers-$(uname -r)
compact_distribution=$(echo $distribution | sed -e 's/\.//g')
wget https://developer.download.nvidia.com/compute/cuda/repos/$compact_distribution/x86_64/cuda-$compact_distribution.pin
mv cuda-$compact_distribution.pin /etc/apt/preferences.d/cuda-repository-pin-600
apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/$compact_distribution/x86_64/7fa2af80.pub
echo "deb http://developer.download.nvidia.com/compute/cuda/repos/$compact_distribution/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list

# Install CUDA Drivers (includes nvidia-driver-X)
apt-get update
apt-get -y install cuda-drivers

sed -i -e 's#PATH="#PATH="/usr/local/cuda-11.2/bin:#g' /etc/environment

cp /lib/udev/rules.d/40-vm-hotadd.rules /etc/udev/rules.d
sed -i -e 's/SUBSYSTEM=="memory", ACTION=="add"/#SUBSYSTEM=="memory", ACTION=="add"/g' /etc/udev/rules.d/40-vm-hotadd.rules

# Add nvidia-docker/nvidia-toolkit if needed
if [ "${UBUNTU_GPU_NVIDIA_TOOLKIT}" == "true" ]; then
    # Use of Docker Image is recommended: https://www.tensorflow.org/install/gpu
    # Many interdependencies can be packed into the image what's difficult for VM only installation.
    # Furthermore, it decreases the Ubuntu GPU Image size massively.
    curl https://get.docker.com | sh \
        && systemctl enable docker

    curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
        && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

    apt-get update
    apt-get install -y nvidia-docker2

    # Test GPU Acess via:
    # docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu python -c "import tensorflow as tf; print('Num GPUs Available: ', len(tf.config.list_physical_devices('GPU')))"
    # docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
fi
